version: '3'
services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  notebook:
    build: ./docker
    container_name: jupyter-notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    depends_on:
      - db
